/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aws.sqs;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        Sender sender = new Sender();
        sender.send("https://sqs.us-east-2.amazonaws.com/777022452897/QueueA", "hello, world!");
    }
}
